openapi: 3.0.1
info:
  title: product-service
  description: product-service AWS Cloud API
  termsOfService: http://swagger.io/terms/
  contact:
    email: Petr_Razvaliaev@epam.com
  version: 1.0.0
servers:
- url: https://43yzo1yuj3.execute-api.eu-west-1.amazonaws.com/develop/
tags:
- name: products
  description: Methods to get and search products
paths:
  /products:
    get:
      tags:
      - products
      summary: Get all list of products
      operationId: getAllProducts
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Products'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
    post:
      tags:
      - products
      summary: Add new product
      operationId: addProduct
      requestBody:
        description: new product data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EditProductData'
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseResult'
        400:
          description: Bad request error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /products/{id}:
    get:
      tags:
      - products
      summary: Get product by id
      operationId: getProductById
      parameters:
      - name: id
        in: path
        description: Id of product
        example: 7567ec4b-b10c-48c5-9345-fc73c48a80a0
        required: true
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        400:
          description: Bad request
          content:
            application/json:
                schema:
                  $ref: '#/components/schemas/BadRequestError'
        404:
          description: Not found
          content:
            application/json:
                schema:
                  $ref: '#/components/schemas/NotFoundError'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          description: Unique id of product
          example: "7567ec4b-b10c-48c5-9345-fc73c48a80a0"
        title:
          type: string
          description: Name of the product displayed on site
          example: Смартфон Xiaomi Redmi 9
        description:
          type: string
          description: Description of the product displayed on site
          example: 6.53" Смартфон Xiaomi Redmi 9 64 ГБ выпускается в сером цвете в корпусе из пластика.
        count:
          type: integer
          description: Amount of product
          example: 98
        imageUrl:
          type: string
          description: Product image url
          example: https://source.unsplash.com/random?sig=2
        price:
          type: number
          description: Price of product
          format: float
          example: 4.5
    Products:
      type: array
      items:
        $ref: '#/components/schemas/Product'
    EditProductData:
      type: object
      properties:
        title: 
          type: string
          description: Title of product
          example: NEW product
        description: 
          type: string
          description: Description of product
          example: description of the NEW product
        price:
          type: number
          description: Price of product
          format: float
          example: 4.5
        imageUrl:
          type: string
          description: Product image url
          example: https://source.unsplash.com/random?sig=2
        count:
          type: integer
          description: Amount of product
          example: 98
    InternalServerError:
      type: object
      properties:
        message:
          type: string
          description: Error message
          example: "Internal server error"
    BadRequestError:
      type: object
      properties:
        message:
          type: string
          description: Error message
          example: "Parameter {id} is required"
    NotFoundError:
      type: object
      properties:
        message:
          type: string
          description: Error message
          example: "Product with 77 is not found"
    ResponseResult:
      type: object
      properties:
        success:
          type: boolean
          description: "Request operation result"
